apiVersion: v1
kind: Service
metadata:
  name: helo-dep
spec:
  selector:
    app: tugasNet   
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80   
  type: ClusterIP      
  
---

apiVersion: v1
kind: Service
metadata:
  name: tugas-service1
spec:
  selector:
    app: tugasNet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: tugas-service1
spec:
  selector:
    app: tugasNet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer